import { useRef } from "preact/hooks";
import { ContentContainer, BarSection } from "./ui/Layout";
import { SendIcon, StopIcon } from "./ui/Icons";

export function ChatInput({
  value,
  onInput,
  onSend,
  onStop,
  canSend,
  streaming,
  disabled,
  textareaRef,
}: {
  value: string;
  onInput: (value: string) => void;
  onSend: () => void;
  onStop: () => void;
  canSend: boolean;
  streaming: boolean;
  disabled?: boolean;
  textareaRef?: { current: HTMLTextAreaElement | null };
}) {
  const fallbackRef = useRef<HTMLTextAreaElement>(null);
  const resolvedTextareaRef = textareaRef ?? fallbackRef;

  function handleInput(e: Event) {
    const el = e.target as HTMLTextAreaElement;
    onInput(el.value);
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 168) + "px";
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      if (canSend) {
        onSend();
        if (resolvedTextareaRef.current) resolvedTextareaRef.current.style.height = "auto";
      }
    }
  }

  function handleSendClick() {
    onSend();
    if (resolvedTextareaRef.current) resolvedTextareaRef.current.style.height = "auto";
  }

  return (
    <BarSection border="top">
      <ContentContainer class="py-3">
        <div class="flex items-end gap-2 bg-neutral-900 rounded-xl border border-neutral-800/80 focus-within:border-neutral-700 transition-colors px-3 py-2">
          <textarea
            ref={resolvedTextareaRef}
            value={value}
            onInput={handleInput}
            onKeyDown={handleKeyDown}
            placeholder="Send a message..."
            rows={1}
            class="flex-1 bg-transparent text-sm text-white placeholder-neutral-400 resize-none outline-none leading-relaxed py-1"
            style="max-height: 168px;"
            disabled={disabled}
          />
          {streaming ? (
            <button
              onClick={onStop}
              class="shrink-0 p-2 rounded-lg bg-neutral-800 text-neutral-300 hover:text-white hover:bg-neutral-700 transition-all"
              title="Stop generating"
            >
              <StopIcon size={16} />
            </button>
          ) : (
            <button
              onClick={handleSendClick}
              disabled={!canSend}
              class="shrink-0 p-2 rounded-lg bg-violet-600 text-white hover:bg-violet-500 transition-all disabled:opacity-30 disabled:cursor-not-allowed disabled:hover:bg-violet-600"
              title="Send message"
            >
              <SendIcon size={16} />
            </button>
          )}
        </div>
        <p class="text-center text-[10px] text-neutral-400 mt-2 select-none">
          Responses generated by AI. Verify important information.
        </p>
      </ContentContainer>
    </BarSection>
  );
}
